//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsyTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_of
    {
        public int id_route { get; set; }
        public int number_of { get; set; }
        public int autosCount { get; set; }
        public int stopCount { get; set; }
        public int passCount { get; set; }
        public int id_path { get; set; }
        public int id_type { get; set; }
    
        public virtual path_of path_of { get; set; }
        public virtual transportType transportType { get; set; }
    }
}
