//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsyTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transportType()
        {
            this.route_of = new HashSet<route_of>();
        }
    
        public int id_type { get; set; }
        public string name_of { get; set; }
        public int avgspeed_of { get; set; }
        public int cost_of { get; set; }
        public int count_of { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<route_of> route_of { get; set; }
    }
}
